#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

generate:
  - types
  - server
namingStrategy: idiomatic
additionalImports:
  - SpeziLocalization
  - SpeziHealthKit
  - SpeziStudyDefinition
typeOverrides:
  schemas:
    InformationalContent: SpeziStudyPlatform.InformationalContent
    InformationalComponentData: SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatform.InformationalContent>
    QuestionnaireContent: SpeziStudyPlatform.QuestionnaireContent
    QuestionnaireComponentData: SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatform.QuestionnaireContent>
    LocalizedString: "SpeziLocalization.LocalizationsDictionary<Swift.String>"
    StudyDetailContent: SpeziStudyPlatform.StudyDetailContent
    StudyDetailData: "SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatform.StudyDetailContent>"
    SampleTypesCollection: "[SpeziHealthKit.SampleTypeProxy]"
    LocalizationKey: SpeziLocalization.LocalizationKey
    StudyConsent: "SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatform.ConsentContent>"
    StudyMetadataCodable: SpeziStudyDefinition.StudyDefinition.Metadata
    StudyVisibility: SpeziStudyPlatform.StudyVisibility
    EnrollmentConditions: SpeziStudyPlatform.EnrollmentConditions
