#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

generate:
  - types
  - server
namingStrategy: idiomatic
additionalImports:
  - SpeziLocalization
  - SpeziHealthKit
  - SpeziStudyDefinition
typeOverrides:
  schemas:
    InformationalContent: SpeziStudyPlatformServer.InformationalContent
    InformationalComponentData: SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatformServer.InformationalContent>
    QuestionnaireContent: SpeziStudyPlatformServer.QuestionnaireContent
    QuestionnaireComponentData: SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatformServer.QuestionnaireContent>
    LocalizedString: "SpeziLocalization.LocalizationsDictionary<Swift.String>"
    StudyDetailContent: SpeziStudyPlatformServer.StudyDetailContent
    StudyDetailData: "SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatformServer.StudyDetailContent>"
    SampleTypesCollection: "[SpeziHealthKit.SampleTypeProxy]"
    LocalizationKey: SpeziLocalization.LocalizationKey
    StudyConsent: "SpeziLocalization.LocalizationsDictionary<SpeziStudyPlatformServer.ConsentContent>"
    StudyMetadataCodable: SpeziStudyDefinition.StudyDefinition.Metadata
    StudyVisibility: SpeziStudyPlatformServer.StudyVisibility
    EnrollmentConditions: SpeziStudyPlatformServer.EnrollmentConditions
